extends SaveableResource
class_name HeatSink

## Accumulates heat that is generated by ship functions and inflicted in combat.
##
## When heat exceeds the maximum capacity of the heat sink, the ship becomes disabled.

## The maximum heat capacity for this sink.
@export var max_heat: float:
    set(value):
        assert(value >= 0.0, "Heat capacity must be non-negative")
        if is_equal_approx(max_heat, value):
            return

        max_heat = value
        self.emit_changed()

## The current heat level.
##
## Unlike other, similar mechanics, this value can exceed [member max_heat], at which point the ship is disabled.
@export var heat: float:
    set(value):
        if is_equal_approx(heat, value):
            return

        heat = maxf(value, 0.0)
        self.emit_changed()
