name: Main

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

env:
  UNITY_VERSION: 2019.3.14f1

jobs:
  # See https://github.com/marketplace/actions/unity-request-activation-file
  # request_activation:
  #   name: Request license activation
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Request manual activation file
  #       id: getManualLicenseFile
  #       uses: webbertakken/unity-request-manual-activation-file@v1.1
  #       with:
  #         unityVersion: ${{ env.UNITY_VERSION }}

  #     - name: Expose as artifact
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: ${{ steps.getManualLicenseFile.outputs.filePath }}
  #         path: ${{ steps.getManualLicenseFile.outputs.filePath }}

  # build:
  #   name: Build for ${{ matrix.targetPlatform }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       targetPlatform:
  #         - StandaloneOSX
  #         - StandaloneWindows
  #         - StandaloneWindows64
  #         - StandaloneLinux64
  #         - WebGL
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/cache@v2
  #       with:
  #         path: Library
  #         key: Library-${{ matrix.targetPlatform }}
  #         restore-keys: |
  #           Library-

  #     - name: Unity build
  #       uses: webbertakken/unity-builder@v1.0
  #       env:
  #         UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  #       with:
  #         unityVersion: ${{ env.UNITY_VERSION }}
  #         targetPlatform: ${{ matrix.targetPlatform }}

  #     - name: Publish to itch.io
  #       if: github.event_name == 'push'
  #       uses: josephbmanley/butler-publish-itchio-action@v1.0.1
  #       env:
  #         BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
  #         CHANNEL: ${{ matrix.targetPlatform }}
  #         ITCH_GAME: Merc
  #         ITCH_USER: jspahrsummers
  #         PACKAGE: build/${{ matrix.targetPlatform }}

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/cache@v2
  #       with:
  #         path: Library
  #         key: Library-Test
  #         restore-keys: |
  #           Library-

  #     - name: Unity tests
  #       uses: webbertakken/unity-test-runner@v1.6
  #       env:
  #         UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  #       with:
  #         unityVersion: ${{ env.UNITY_VERSION }}

  #     - name: Upload test artifacts
  #       if: always()
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: Test results
  #         path: artifacts

  deploy-server:
    name: Deploy server
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      DDCLIENT_CONF: ${{ secrets.DDCLIENT_CONF }}
      GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
      GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
      IMAGE_NAME: merc-server

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-StandaloneLinux64
          restore-keys: |
            Library-

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "297.0.1"
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          project_id: ${{ secrets.GCE_PROJECT }}

      - name: Set up gcloud as Docker credential helper
        run: gcloud --quiet auth configure-docker

      # TODO: Build specifically for headless operation, to cut down size
      - name: Build headless Linux server
        uses: webbertakken/unity-builder@v1.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: StandaloneLinux64

      - name: Dockerize
        run: docker build -f Server/Dockerfile --build-arg DDCLIENT_CONF="$DDCLIENT_CONF" --tag "gcr.io/$GCLOUD_PROJECT/$IMAGE_NAME:$GITHUB_SHA" .

      - name: Publish to GCR
        run: docker push "gcr.io/$GCLOUD_PROJECT/$IMAGE_NAME:$GITHUB_SHA"

      - name: Deploy to GCE
        run: gcloud compute instances update-container "$GCE_INSTANCE" --container-image="gcr.io/$GCLOUD_PROJECT/$IMAGE_NAME:$GITHUB_SHA"
