on:
  pull_request: {}
  push:
    branches: [master]

env:
  UNITY_VERSION: 2019.3.14f1

jobs:
  # See https://github.com/marketplace/actions/unity-request-activation-file
  # request_activation:
  #   name: Request license activation
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Request manual activation file
  #       id: getManualLicenseFile
  #       uses: webbertakken/unity-request-manual-activation-file@v1.1
  #       with:
  #         unityVersion: ${{ env.UNITY_VERSION }}

  #     - name: Expose as artifact
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: ${{ steps.getManualLicenseFile.outputs.filePath }}
  #         path: ${{ steps.getManualLicenseFile.outputs.filePath }}

  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows
          - StandaloneWindows64
          - WebGL
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-

      - name: Unity build
        uses: webbertakken/unity-builder@v1.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Publish to itch.io
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        uses: josephbmanley/butler-publish-itchio-action@v1.0.1
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: ${{ matrix.targetPlatform }}
          ITCH_GAME: Merc
          ITCH_USER: jspahrsummers
          PACKAGE: build/${{ matrix.targetPlatform }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Test
          restore-keys: |
            Library-

      - name: Unity tests
        uses: webbertakken/unity-test-runner@v1.6
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ env.UNITY_VERSION }}

      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Test results
          path: artifacts
