name: Test
on: [push, pull_request]

env:
  # Choose from available tags: https://hub.docker.com/r/gableroux/unity3d
  UNITY_VERSION: 2019.4.8f1

jobs:
  # See https://github.com/marketplace/actions/unity-request-activation-file
  # request_activation:
  #   name: Request license activation
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Request manual activation file
  #       id: getManualLicenseFile
  #       uses: webbertakken/unity-request-manual-activation-file@v1.1
  #       with:
  #         unityVersion: ${{ env.UNITY_VERSION }}

  #     - name: Expose as artifact
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: ${{ steps.getManualLicenseFile.outputs.filePath }}
  #         path: ${{ steps.getManualLicenseFile.outputs.filePath }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Test
          restore-keys: |
            Library-

      - name: Unity tests
        uses: webbertakken/unity-test-runner@v1.6
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ env.UNITY_VERSION }}

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test results
          path: artifacts
